jwt.secret=ShineSecretKey2025ShineSecretKey2025ShineSecretKey2025ShineSecretKey2025
jwt.expiration.ms=2592000000

# ── Configuración SMTP para EmailService ──────────────────────────────────────
# Gmail ejemplo: host=smtp.gmail.com, port=587, starttls=true
# Usa una "App Password" de Google si tienes 2FA activado.
mail.host=smtp.gmail.com
mail.port=587
mail.starttls=true
mail.username=izankarimshine@gmail.com
mail.password=Shine2025
mail.from=izankarimshine@gmail.com
