ALTER TABLE fichaje ALTER COLUMN id_usuario DROP NOT NULL;
ALTER TABLE fichaje ADD COLUMN IF NOT EXISTS empleado_email VARCHAR(100);
ALTER TABLE fichaje ADD COLUMN IF NOT EXISTS empleado_nombre VARCHAR(150)
